### ISSUE TITLE
KZones Shortcuts do not work on Plasma 6

### ISSUE THREAD

**Issue by mphartzheim** [gerritdevriese/kzones#62] opened 2024-03-06 14:04 UTC
Nobara 39 updated to KDE Plasma 6 and the KZones shortcuts are no longer functioning.

I'm a linux newbie so please let me know how I can help you.

Thanks!

**Comment by gerritdevriese** [comment] 2024-03-06 19:52
KZones will not work at all on Plasma 6 until it is rewritten because the KWin API changed a lot 🙁
I'll see when I can make time for this.

**Comment by mphartzheim** [comment] 2024-03-06 19:55
Thanks for the update!

**Comment by kotek14** [comment] 2024-03-13 01:16
> KZones will not work at all on Plasma 6 until it is rewritten because the KWin API changed a lot 🙁 I'll see when I can make time for this.

Thank you for the update. Fingers crossed.
I've been relying on KZones for over a year. It is hands down the best snap layout replacement on Linux.

**Comment by fynzhak** [comment] 2024-03-31 17:46
For anyone watching this issue, I opened a PR with my attempt to port to Plasma 6. It's working for me so far, but I can't guarantee I didn't introduce any regressions.

Maybe it's helpful though!

https://github.com/gerritdevriese/kzones/pull/63

**Comment by gerritdevriese** [comment] 2024-03-31 18:53
> For anyone watching this issue, I opened a PR with my attempt to port to Plasma 6. It's working for me so far, but I can't guarantee I didn't introduce any regressions.
> 
> Maybe it's helpful though!
> 
> #63

Thank you so much 🙏 Just tested it and seems to be working fine and I can't find any regressions. I will accept your PR right away so other people can test.

I actually also started porting a few days ago, but then I fell into a rabbit hole that is the KWin Tiling API and got somewhat demotivated 😅

**Comment by principis** [comment] 2024-03-31 21:46
There seem to be some issues when 0.7 is installed system wide in `/usr/share/kwin/scripts`, but not when installed per-user in `~/.local/share/kwin/scripts`. (0.6 works fine)

error message:
```
Mar 31 23:13:20 MarkVI kwin_wayland[83805]: kwin_scripting: Component failed to load:  (file:///usr/share/kwin/scripts/kzones/contents/ui/main.qml: Library import requires a version, file:///usr/share/kwin/scripts/kzones/contents/ui/main.qml: Library import requires a version, file:///usr/share/kwin/scripts/kzones/contents/ui/main.qml: Library import requires a version, file:///usr/share/kwin/scripts/kzones/contents/ui/main.qml: Library import requires a version, file:///usr/share/kwin/scripts/kzones/contents/ui/main.qml:5:28: Library import requires a version
                                                import org.kde.kirigami as Kirigami
                                                                           ^, file:///usr/share/kwin/scripts/kzones/contents/ui/main.qml: Library import requires a version, file:///usr/share/kwin/scripts/kzones/contents/ui/main.qml:7:37: Library import requires a version
                                                import org.kde.plasma.components as PlasmaComponents
                                                                                    ^, file:///usr/share/kwin/scripts/kzones/contents/ui/main.qml:8:31: Library import requires a version
                                                import org.kde.plasma.core as PlasmaCore
                                                                              ^, file:///usr/share/kwin/scripts/kzones/contents/ui/main.qml:9:41: Library import requires a version
                                                import org.kde.plasma.plasma5support as Plasma5Support
                                                                                        ^)
```

I would like to package kzones for Fedora, but unfortunately this blocks me from doing so...

**Comment by fynzhak** [comment] 2024-03-31 22:16
@principis , sorry, I think that's my mistake. I removed the version numbers since it was giving me some trouble initially, but perhaps I should have left them in. Also, this was ported to Plasma 6 so I'm not sure if it will work at all on Plasma 5. gerritdevriese updated the README to mention 6 or higher.

@gerritdevriese , should the versions be added back though? Another folly of me not fully understanding QML :sweat_smile:

**Comment by principis** [comment] 2024-03-31 22:22
@fynzhak No worries! Also, it definitely doesn't have to work on Plasma 5 :slightly_smiling_face:. I intend to test on Plasma 6, but since the per-user version works fine, I figured, let's post it here already.

**Comment by principis** [comment] 2024-04-01 09:58
@fynzhak Seems to work on Plasma 6! Sorry for the confusion.

**Comment by gerritdevriese** [comment] 2024-04-01 14:08
> @gerritdevriese , should the versions be added back though? Another folly of me not fully understanding QML 😅

Nah I don't think so, I just removed them from the Indicator as well, doesn't seem to have any impact on Plasma 6.

---

Anyway, if no one encounters any issues in the following days I will update the KDE Store page.

**Comment by diederikgist** [comment] 2024-04-01 19:32
Just upgrade this weekend to Plasma 6. Was trying to get KZones back on track. I just installed the latest version from git (few hours old). But I'm also experiencing issues with my shortcuts. Toggle throught my layouts (control alt + D) works, but putting my active window to a spot in my layout (control alt 1/2 etc) does nothing. I also tried binding this shortcut to a different key combination without success. 

Anything else I can try?

**Comment by gerritdevriese** [comment] 2024-04-01 19:57
> Just upgrade this weekend to Plasma 6. Was trying to get KZones back on track. I just installed the latest version from git (few hours old). But I'm also experiencing issues with my shortcuts. Toggle throught my layouts (control alt + D) works, but putting my active window to a spot in my layout (control alt 1/2 etc) does nothing. I also tried binding this shortcut to a different key combination without success.
> 
> Anything else I can try?

Seems that during the port those shortcuts were accidentally renamed to `Move active window to #` instead of `Move active window to zone #`, so you will probably have some duplicate shortcuts in your shortcuts manager:

![image](https://github.com/gerritdevriese/kzones/assets/1899386/0849ea55-7738-452f-8957-29489993d495)

I've fixed the naming on the main branch but if you don't want to rebuild you can rebind the shortcuts manually.

Btw you can run `qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.cleanUp` if you want to get rid of those duplicate shortcuts.

**Comment by fynzhak** [comment] 2024-04-01 21:35
Ooops! Looks like I missed selecting a word when copying the string. Good catch!

**Comment by diederikgist** [comment] 2024-04-02 07:22
After a git pull my shortcuts are working again! Thanks for you efforts! :+1:

**Comment by gerritdevriese** [comment] 2024-04-03 20:08
Version 0.7 has been released on GitHub and the KDE Store, closing this issue.

**Closed by gerritdevriese** 2024-04-03 20:08 UTC
